services:
  moviedb:
    build:
      context: .
      args:
        JAR_FILE: target/movieDB-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    volumes:
      - moviedb-data:/data

volumes:
  moviedb-data:
