spring:
  application:
    name: movieDB
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
      url: jdbc:sqlite:database.db
      driver-class-name: org.sqlite.JDBC

